export const karigarOrder = {
  "Karigar A": [1, 3, 4, 19],
  "Karigar B": [2, 20],
  "Karigar D": [5],
  "Karigar Y": [6, 8, 9],
  "Karigar U": [7],
  "Karigar H": [10],
  "Karigar N": [11, 14],
  "Karigar L": [12],
  "Karigar M": [13],
  "Karigar O": [15],
  "Karigar P": [16],
  "Karigar Q": [17],
  "Karigar R": [18],
};
