export const orders = [
  {
    ID: 1,
    client: "Client 1",
    karat: "22K",
    weight: "15g",
    image: "https://example.com/image1.jpg",
    description: "Description for order 1",
    datePlaced: "01-08-2024",
    endDate: "01-08-2024",
    karigar: "Karigar A",
    status: "Completed",
  },
  {
    ID: 2,
    client: "Client 2",
    karat: "18K",
    weight: "10g",
    image: "https://example.com/image2.jpg",
    description: "Description for order 2",
    datePlaced: "02-08-2024",
    endDate: "02-08-2024",
    karigar: "Karigar B",
    status: "Active",
  },
  {
    ID: 3,
    client: "Client 3",
    karat: "20K",
    weight: "20g",
    image: "https://example.com/image3.jpg",
    description: "Description for order 3",
    datePlaced: "03-08-2024",
    endDate: "03-08-2024",
    karigar: "Karigar A",
    status: "Active",
  },
  {
    ID: 4,
    client: "Client 4",
    karat: "22K",
    weight: "12g",
    image: "https://example.com/image4.jpg",
    description: "Description for order 4",
    datePlaced: "04-08-2024",
    endDate: "04-08-2024",
    karigar: "Karigar A",
    status: "Completed",
  },
  {
    ID: 5,
    client: "Client 5",
    karat: "18K",
    weight: "8g",
    image: "https://example.com/image5.jpg",
    description: "Description for order 5",
    datePlaced: "05-08-2024",
    endDate: "05-08-2024",
    karigar: "Karigar D",
    status: "Active",
  },
  {
    ID: 6,
    client: "Client 6",
    karat: "22K",
    weight: "18g",
    image: "https://example.com/image6.jpg",
    description: "Description for order 6",
    datePlaced: "06-08-2024",
    endDate: "06-08-2024",
    karigar: "Karigar Y",
    status: "Completed",
  },
  {
    ID: 7,
    client: "Client 7",
    karat: "24K",
    weight: "25g",
    image: "https://example.com/image7.jpg",
    description: "Description for order 7",
    datePlaced: "07-08-2024",
    endDate: "07-08-2024",
    karigar: "Karigar U",
    status: "Active",
  },
  {
    ID: 8,
    client: "Client 8",
    karat: "18K",
    weight: "14g",
    image: "https://example.com/image8.jpg",
    description: "Description for order 8",
    datePlaced: "08-08-2024",
    endDate: "08-08-2024",
    karigar: "Karigar Y",
    status: "Active",
  },
  {
    ID: 9,
    client: "Client 9",
    karat: "22K",
    weight: "30g",
    image: "https://example.com/image9.jpg",
    description: "Description for order 9",
    datePlaced: "09-08-2024",
    endDate: "09-08-2024",
    karigar: "Karigar Y",
    status: "Completed",
  },
  {
    ID: 10,
    client: "Client 10",
    karat: "24K",
    weight: "5g",
    image: "https://example.com/image10.jpg",
    description: "Description for order 10",
    datePlaced: "10-08-2024",
    endDate: "10-08-2024",
    karigar: "Karigar H",
    status: "Completed",
  },
  {
    ID: 11,
    client: "Client 11",
    karat: "22K",
    weight: "15g",
    image: "https://example.com/image11.jpg",
    description: "Description for order 11",
    datePlaced: "11-08-2024",
    endDate: "11-08-2024",
    karigar: "Karigar N",
    status: "Active",
  },
  {
    ID: 12,
    client: "Client 12",
    karat: "18K",
    weight: "10g",
    image: "https://example.com/image12.jpg",
    description: "Description for order 12",
    datePlaced: "12-08-2024",
    endDate: "12-08-2024",
    karigar: "Karigar L",
    status: "Completed",
  },
  {
    ID: 13,
    client: "Client 13",
    karat: "24K",
    weight: "20g",
    image: "https://example.com/image13.jpg",
    description: "Description for order 13",
    datePlaced: "13-08-2024",
    endDate: "13-08-2024",
    karigar: "Karigar M",
    status: "Active",
  },
  {
    ID: 14,
    client: "Client 14",
    karat: "22K",
    weight: "12g",
    image: "https://example.com/image14.jpg",
    description: "Description for order 14",
    datePlaced: "14-08-2024",
    endDate: "14-08-2024",
    karigar: "Karigar N",
    status: "Active",
  },
  {
    ID: 15,
    client: "Client 15",
    karat: "18K",
    weight: "8g",
    image: "https://example.com/image15.jpg",
    description: "Description for order 15",
    datePlaced: "15-08-2024",
    endDate: "15-08-2024",
    karigar: "Karigar O",
    status: "Completed",
  },
  {
    ID: 16,
    client: "Client 16",
    karat: "22K",
    weight: "18g",
    image: "https://example.com/image16.jpg",
    description: "Description for order 16",
    datePlaced: "16-08-2024",
    endDate: "16-08-2024",
    karigar: "Karigar P",
    status: "Completed",
  },
  {
    ID: 17,
    client: "Client 17",
    karat: "24K",
    weight: "25g",
    image: "https://example.com/image17.jpg",
    description: "Description for order 17",
    datePlaced: "17-08-2024",
    endDate: "17-08-2024",
    karigar: "Karigar Q",
    status: "Completed",
  },
  {
    ID: 18,
    client: "Client 18",
    karat: "18K",
    weight: "14g",
    image: "https://example.com/image18.jpg",
    description: "Description for order 18",
    datePlaced: "18-08-2024",
    endDate: "18-08-2024",
    karigar: "Karigar R",
    status: "Active",
  },
  {
    ID: 19,
    client: "Client 19",
    karat: "22K",
    weight: "30g",
    image: "https://example.com/image19.jpg",
    description: "Description for order 19",
    datePlaced: "19-08-2024",
    endDate: "19-08-2024",
    karigar: "Karigar A",
    status: "Active",
  },
  {
    ID: 20,
    client: "Client 20",
    karat: "24K",
    weight: "5g",
    image: "https://example.com/image20.jpg",
    description: "Description for order 20",
    datePlaced: "20-08-2024",
    endDate: "20-08-2024",
    karigar: "Karigar B",
    status: "Completed",
  },
];
