export const orders = [
  {
    ID: 1,
    client: "Client 1",
    karat: "22K",
    weight: "15g",
    image: "https://example.com/image1.jpg",
    description: "Description for order 1",
    date_placed: "2024-08-01",
    end_date: "2024-08-01",
    karigar: "Karigar A",
    status: "Completed",
  },
  {
    ID: 2,
    client: "Client 2",
    karat: "18K",
    weight: "10g",
    image: "https://example.com/image2.jpg",
    description: "Description for order 2",
    date_placed: "2024-08-02",
    end_date: "2024-08-02",
    karigar: "Karigar B",
    status: "Active",
  },
  {
    ID: 3,
    client: "Client 3",
    karat: "24K",
    weight: "20g",
    image: "https://example.com/image3.jpg",
    description: "Description for order 3",
    date_placed: "2024-08-03",
    end_date: "2024-08-03",
    karigar: "Karigar C",
    status: "Active",
  },
  {
    ID: 4,
    client: "Client 4",
    karat: "22K",
    weight: "12g",
    image: "https://example.com/image4.jpg",
    description: "Description for order 4",
    date_placed: "2024-08-04",
    end_date: "2024-08-04",
    karigar: "Karigar D",
    status: "Completed",
  },
  {
    ID: 5,
    client: "Client 5",
    karat: "18K",
    weight: "8g",
    image: "https://example.com/image5.jpg",
    description: "Description for order 5",
    date_placed: "2024-08-05",
    end_date: "2024-08-05",
    karigar: "Karigar E",
    status: "Active",
  },
  {
    ID: 6,
    client: "Client 6",
    karat: "22K",
    weight: "18g",
    image: "https://example.com/image6.jpg",
    description: "Description for order 6",
    date_placed: "2024-08-06",
    end_date: "2024-08-06",
    karigar: "Karigar F",
    status: "Completed",
  },
  {
    ID: 7,
    client: "Client 7",
    karat: "24K",
    weight: "25g",
    image: "https://example.com/image7.jpg",
    description: "Description for order 7",
    date_placed: "2024-08-07",
    end_date: "2024-08-07",
    karigar: "Karigar G",
    status: "Active",
  },
  {
    ID: 8,
    client: "Client 8",
    karat: "18K",
    weight: "14g",
    image: "https://example.com/image8.jpg",
    description: "Description for order 8",
    date_placed: "2024-08-08",
    end_date: "2024-08-08",
    karigar: "Karigar H",
    status: "Active",
  },
  {
    ID: 9,
    client: "Client 9",
    karat: "22K",
    weight: "30g",
    image: "https://example.com/image9.jpg",
    description: "Description for order 9",
    date_placed: "2024-08-09",
    end_date: "2024-08-09",
    karigar: "Karigar I",
    status: "Completed",
  },
  {
    ID: 10,
    client: "Client 10",
    karat: "24K",
    weight: "5g",
    image: "https://example.com/image10.jpg",
    description: "Description for order 10",
    date_placed: "2024-08-10",
    end_date: "2024-08-10",
    karigar: "Karigar J",
    status: "Completed",
  },
  {
    ID: 11,
    client: "Client 11",
    karat: "22K",
    weight: "15g",
    image: "https://example.com/image11.jpg",
    description: "Description for order 11",
    date_placed: "2024-08-11",
    end_date: "2024-08-11",
    karigar: "Karigar K",
    status: "Active",
  },
  {
    ID: 12,
    client: "Client 12",
    karat: "18K",
    weight: "10g",
    image: "https://example.com/image12.jpg",
    description: "Description for order 12",
    date_placed: "2024-08-12",
    end_date: "2024-08-12",
    karigar: "Karigar L",
    status: "Completed",
  },
  {
    ID: 13,
    client: "Client 13",
    karat: "24K",
    weight: "20g",
    image: "https://example.com/image13.jpg",
    description: "Description for order 13",
    date_placed: "2024-08-13",
    end_date: "2024-08-13",
    karigar: "Karigar M",
    status: "Active",
  },
  {
    ID: 14,
    client: "Client 14",
    karat: "22K",
    weight: "12g",
    image: "https://example.com/image14.jpg",
    description: "Description for order 14",
    date_placed: "2024-08-14",
    end_date: "2024-08-14",
    karigar: "Karigar N",
    status: "Active",
  },
  {
    ID: 15,
    client: "Client 15",
    karat: "18K",
    weight: "8g",
    image: "https://example.com/image15.jpg",
    description: "Description for order 15",
    date_placed: "2024-08-15",
    end_date: "2024-08-15",
    karigar: "Karigar O",
    status: "Completed",
  },
  {
    ID: 16,
    client: "Client 16",
    karat: "22K",
    weight: "18g",
    image: "https://example.com/image16.jpg",
    description: "Description for order 16",
    date_placed: "2024-08-16",
    end_date: "2024-08-16",
    karigar: "Karigar P",
    status: "Completed",
  },
  {
    ID: 17,
    client: "Client 17",
    karat: "24K",
    weight: "25g",
    image: "https://example.com/image17.jpg",
    description: "Description for order 17",
    date_placed: "2024-08-17",
    end_date: "2024-08-17",
    karigar: "Karigar Q",
    status: "Completed",
  },
  {
    ID: 18,
    client: "Client 18",
    karat: "18K",
    weight: "14g",
    image: "https://example.com/image18.jpg",
    description: "Description for order 18",
    date_placed: "2024-08-18",
    end_date: "2024-08-18",
    karigar: "Karigar R",
    status: "Active",
  },
  {
    ID: 19,
    client: "Client 19",
    karat: "22K",
    weight: "30g",
    image: "https://example.com/image19.jpg",
    description: "Description for order 19",
    date_placed: "2024-08-19",
    end_date: "2024-08-19",
    karigar: "Karigar S",
    status: "Active",
  },
  {
    ID: 20,
    client: "Client 20",
    karat: "24K",
    weight: "5g",
    image: "https://example.com/image20.jpg",
    description: "Description for order 20",
    date_placed: "2024-08-20",
    end_date: "2024-08-20",
    karigar: "Karigar T",
    status: "Completed",
  },
];
